In [2]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\yr714\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\yr714\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\yr714\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\yr714\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\yr714\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\yr714\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

roll  = pd.Series([1, 2, 3, 4, 5])
name  = pd.Series(['Sia', 'Ravi', 'Geet', 'Ajeenkya', 'Avinash'])
marks = pd.Series([85, 67, 59, 40, 90])

In [4]:
df = pd.DataFrame({
    'id': roll,
    'name': name,
    'marks': marks
})

In [5]:
df

   id      name  marks
0   1       Sia     85
1   2      Ravi     67
2   3      Geet     59
3   4  Ajeenkya     40
4   5   Avinash     90

In [6]:
df.ndim

2

In [7]:
df.shape

(5, 3)

In [8]:
df.size

15

In [9]:
df.columns

Index(['id', 'name', 'marks'], dtype='object')

In [10]:
"""

url -> https://mitu.co.in/dataset ->

_IncompleteInputError: incomplete input (3010987261.py, line 1)

In [11]:
pwd

'C:\\Users\\yr714\\internshiplearning'

In [12]:
df = pd.read_csv("student.csv")

In [13]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [14]:
df.shape

(10, 5)

In [15]:
df.size

50

In [16]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [17]:
df = pd.read_csv("student1.csv")

In [18]:
df

    1     anil  TE  56.77  22
0   2     amit  TE  59.77  21
1   3   aniket  BE  76.88  19
2   4  ajinkya  TE  69.66  20
3   5     asha  TE  63.28  20
4   6   ayesha  BE  49.55  20
5   7     amar  BE  65.34  19
6   8    amita  BE  68.33  23
7   9     amol  TE  56.75  20
8  10    anmol  BE  78.66  21

In [19]:
df.shape

(9, 5)

In [22]:
df.columns

Index(['1', 'anil', 'TE', '56.77', '22'], dtype='object')

In [23]:
col  = ['roll', 'name', 'class', 'marks', 'age']

In [24]:
df = pd.read_csv('student1.csv', names = col)
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [31]:
df = pd.read_csv("student3.tsv", sep="\t")

In [32]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21