In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('student3.csv')

In [3]:
df

    roll     name class  marks    age
0      1     anil    TE   56.77  22.0
1      2     amit    TE   59.77  21.0
2      3   aniket    BE   76.88  19.0
3      4  ajinkya    TE   69.66  20.0
4      5     asha    TE   63.28   NaN
5      6   ayesha    BE     NaN  20.0
6      7     amar    BE   65.34  19.0
7      8    Amita    be   68.33  23.0
8      9     amol    TE   56.75  20.0
9      9     amol    TE   56.75  20.0
10    10    anmol    BE   78.66   NaN
11    11   surbhi    TE     NaN  23.0
12    12    Sujay    TE   74.12  22.0
13    13  subhash    be   88.45  21.0
14    14   sachin   NaN   59.33  21.0
15    15  shalini    TE   63.45  20.0

In [4]:
df['name']

0        anil
1        amit
2      aniket
3     ajinkya
4        asha
5      ayesha
6        amar
7       Amita
8        amol
9        amol
10      anmol
11     surbhi
12      Sujay
13    subhash
14     sachin
15    shalini
Name: name, dtype: object

In [5]:
df['name']= df['name'].str.title()

In [6]:
df

    roll     name class  marks    age
0      1     Anil    TE   56.77  22.0
1      2     Amit    TE   59.77  21.0
2      3   Aniket    BE   76.88  19.0
3      4  Ajinkya    TE   69.66  20.0
4      5     Asha    TE   63.28   NaN
5      6   Ayesha    BE     NaN  20.0
6      7     Amar    BE   65.34  19.0
7      8    Amita    be   68.33  23.0
8      9     Amol    TE   56.75  20.0
9      9     Amol    TE   56.75  20.0
10    10    Anmol    BE   78.66   NaN
11    11   Surbhi    TE     NaN  23.0
12    12    Sujay    TE   74.12  22.0
13    13  Subhash    be   88.45  21.0
14    14   Sachin   NaN   59.33  21.0
15    15  Shalini    TE   63.45  20.0

In [11]:
df['class']

0      Te
1      Te
2      Be
3      Te
4      Te
5      Be
6      Be
7      Be
8      Te
9      Te
10     Be
11     Te
12     Te
13     Be
14    NaN
15     Te
Name: class, dtype: object

In [23]:
df['class'] = df['class'].str.upper()

In [24]:
df

    roll     name class  marks    age
0      1     Anil    TE   56.77  22.0
1      2     Amit    TE   59.77  21.0
2      3   Aniket    BE   76.88  19.0
3      4  Ajinkya    TE   69.66  20.0
4      5     Asha    TE   63.28   NaN
5      6   Ayesha    BE     NaN  20.0
6      7     Amar    BE   65.34  19.0
7      8    Amita    BE   68.33  23.0
8      9     Amol    TE   56.75  20.0
9      9     Amol    TE   56.75  20.0
10    10    Anmol    BE   78.66   NaN
11    11   Surbhi    TE     NaN  23.0
12    12    Sujay    TE   74.12  22.0
13    13  Subhash    BE   88.45  21.0
14    14   Sachin   NaN   59.33  21.0
15    15  Shalini    TE   63.45  20.0

In [25]:
df.columns

Index(['roll', 'name', 'class', 'marks ', 'age'], dtype='object')

In [29]:
df.columns = df.columns.str.strip()

In [30]:
df['marks']

0     56.77
1     59.77
2     76.88
3     69.66
4     63.28
5       NaN
6     65.34
7     68.33
8     56.75
9     56.75
10    78.66
11      NaN
12    74.12
13    88.45
14    59.33
15    63.45
Name: marks, dtype: float64

In [31]:
# duplicates value

In [35]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
dtype: bool

In [38]:
df.duplicated().sum()

np.int64(1)

In [39]:
df.drop_duplicates(inplace=True)

In [40]:
df

    roll     name class  marks   age
0      1     Anil    TE  56.77  22.0
1      2     Amit    TE  59.77  21.0
2      3   Aniket    BE  76.88  19.0
3      4  Ajinkya    TE  69.66  20.0
4      5     Asha    TE  63.28   NaN
5      6   Ayesha    BE    NaN  20.0
6      7     Amar    BE  65.34  19.0
7      8    Amita    BE  68.33  23.0
8      9     Amol    TE  56.75  20.0
10    10    Anmol    BE  78.66   NaN
11    11   Surbhi    TE    NaN  23.0
12    12    Sujay    TE  74.12  22.0
13    13  Subhash    BE  88.45  21.0
14    14   Sachin   NaN  59.33  21.0
15    15  Shalini    TE  63.45  20.0

In [41]:
# missing values

In [42]:
df.count()

roll     15
name     15
class    14
marks    13
age      13
dtype: int64

In [44]:
df.isnull().sum()

roll     0
name     0
class    1
marks    2
age      2
dtype: int64

In [45]:
df.isnull().sum().sum()

np.int64(5)

In [46]:
# removing rows with null values

In [47]:
df.dropna()

    roll     name class  marks   age
0      1     Anil    TE  56.77  22.0
1      2     Amit    TE  59.77  21.0
2      3   Aniket    BE  76.88  19.0
3      4  Ajinkya    TE  69.66  20.0
6      7     Amar    BE  65.34  19.0
7      8    Amita    BE  68.33  23.0
8      9     Amol    TE  56.75  20.0
12    12    Sujay    TE  74.12  22.0
13    13  Subhash    BE  88.45  21.0
15    15  Shalini    TE  63.45  20.0

In [49]:
df['marks'].fillna(45)
# fill with avg marks

0     56.77
1     59.77
2     76.88
3     69.66
4     63.28
5     45.00
6     65.34
7     68.33
8     56.75
10    78.66
11    45.00
12    74.12
13    88.45
14    59.33
15    63.45
Name: marks, dtype: float64

In [50]:
df['marks'].fillna(df['marks'].mean())

0     56.770000
1     59.770000
2     76.880000
3     69.660000
4     63.280000
5     67.753077
6     65.340000
7     68.330000
8     56.750000
10    78.660000
11    67.753077
12    74.120000
13    88.450000
14    59.330000
15    63.450000
Name: marks, dtype: float64

In [51]:
df['age'].fillna(df['age'].median())

0     22.0
1     21.0
2     19.0
3     20.0
4     21.0
5     20.0
6     19.0
7     23.0
8     20.0
10    21.0
11    23.0
12    22.0
13    21.0
14    21.0
15    20.0
Name: age, dtype: float64

In [52]:
# fill

In [53]:
df['class'].mode()

0    TE
Name: class, dtype: object

In [54]:
df['class'].fillna(df['class'].mode())

0      TE
1      TE
2      BE
3      TE
4      TE
5      BE
6      BE
7      BE
8      TE
10     BE
11     TE
12     TE
13     BE
14    NaN
15     TE
Name: class, dtype: object

In [55]:
df.ffill()

    roll     name class  marks   age
0      1     Anil    TE  56.77  22.0
1      2     Amit    TE  59.77  21.0
2      3   Aniket    BE  76.88  19.0
3      4  Ajinkya    TE  69.66  20.0
4      5     Asha    TE  63.28  20.0
5      6   Ayesha    BE  63.28  20.0
6      7     Amar    BE  65.34  19.0
7      8    Amita    BE  68.33  23.0
8      9     Amol    TE  56.75  20.0
10    10    Anmol    BE  78.66  20.0
11    11   Surbhi    TE  78.66  23.0
12    12    Sujay    TE  74.12  22.0
13    13  Subhash    BE  88.45  21.0
14    14   Sachin    BE  59.33  21.0
15    15  Shalini    TE  63.45  20.0

In [56]:
df.bfill()

    roll     name class  marks   age
0      1     Anil    TE  56.77  22.0
1      2     Amit    TE  59.77  21.0
2      3   Aniket    BE  76.88  19.0
3      4  Ajinkya    TE  69.66  20.0
4      5     Asha    TE  63.28  20.0
5      6   Ayesha    BE  65.34  20.0
6      7     Amar    BE  65.34  19.0
7      8    Amita    BE  68.33  23.0
8      9     Amol    TE  56.75  20.0
10    10    Anmol    BE  78.66  23.0
11    11   Surbhi    TE  74.12  23.0
12    12    Sujay    TE  74.12  22.0
13    13  Subhash    BE  88.45  21.0
14    14   Sachin    TE  59.33  21.0
15    15  Shalini    TE  63.45  20.0

In [57]:
df.bfill(inplace=True)

In [58]:
df.isnull().sum()

roll     0
name     0
class    0
marks    0
age      0
dtype: int64

In [ ]:
##