In [1]:
# loan approval expert system

In [14]:
def approval_loan(income, credit_score,existing_loan):
    if income >= 50000 and credit_score >= 700 and not existing_loan:
        return "loan Approved"
    elif income >= 30000 and credit_score >= 650:
        return "further review required"
    else:
        return "loan rejected"

In [15]:
income = 700000
credit_score = 750
existing_loan = False

In [16]:
# Inference engine

In [17]:
decision = approval_loan(
    income,
    credit_score,
    existing_loan
)

In [18]:
decision

'loan Approved'

In [5]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\yr714\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\yr714\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\yr714\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\yr714\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\yr714\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\yr714\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
# create sample  data

In [12]:
data = {
    "hours_studies":[1,2,3,4,5,6,7,8,9,10],
    "marks":[35,40,50,55,60,65,70,78,85,90]
}

In [13]:
import pandas as pd

In [14]:
df = pd.DataFrame(data)

print(df)

   hours_studies  marks
0              1     35
1              2     40
2              3     50
3              4     55
4              5     60
5              6     65
6              7     70
7              8     78
8              9     85
9             10     90

In [15]:
# separate input (x) and output(y)

In [16]:
x = df[["hours_studies"]]
y = df[["marks"]]

In [17]:
print(x)

   hours_studies
0              1
1              2
2              3
3              4
4              5
5              6
6              7
7              8
8              9
9             10

In [18]:
print(y)

   marks
0     35
1     40
2     50
3     55
4     60
5     65
6     70
7     78
8     85
9     90

In [21]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\yr714\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in c:\users\yr714\anaconda3\lib\site-packages (from scikit-learn) (2.3.5)
Requirement already satisfied: scipy>=1.8.0 in c:\users\yr714\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\yr714\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\yr714\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Note: you may need to restart the kernel to use updated packages.

In [22]:
import sklearn
print(sklearn.__version__)

1.7.2

In [23]:
# split data into training and testing

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [26]:
print(X_train)

   hours_studies
5              6
0              1
7              8
2              3
9             10
4              5
3              4
6              7

In [27]:
print(X_test)

   hours_studies
8              9
1              2

In [28]:
print(y_train)

   marks
5     65
0     35
7     78
2     50
9     90
4     60
3     55
6     70

In [29]:
print(y_test)

   marks
8     85
1     40

In [71]:
# Import LinearRegression

In [72]:
from sklearn.linear_model import LinearRegression

In [73]:
# create and train model

In [74]:
model =   LinearRegression()

In [75]:
model.fit(X_train,y_train)

LinearRegression()

In [76]:
# make predictions

In [77]:
y_pred = model.predict(X_test)

In [78]:
y_pred

array([[83.54310345],
       [42.20689655]])

In [79]:
y_test

   marks
8     85
1     40

In [80]:
from sklearn.metrics import mean_squared_error

In [81]:
mean_squared_error(y_test,y_pred)

3.496469976218767

In [82]:
# predicted for new value

In [83]:
new_hours = pd.DataFrame({"Hours_Studies":[7.5]})

In [84]:
new_hours

   Hours_Studies
0            7.5

In [86]:
predicted_marks = model.predict(new_hours)

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- Hours_Studies
Feature names seen at fit time, yet now missing:
- hours_studies

In [62]:
# y = mx + c

In [63]:
# x = Input value
# y = predicted value
# m = slope
# c = intercept